# Generated by Django 5.1.4 on 2025-06-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandartTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpublications',
            name='tags',
        ),
        migrations.AddField(
            model_name='userpublications',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_page.standarttags'),
        ),
    ]
